"""Render measured V2 results (JSON) into the tables in docs/. No number in these tables is typed by hand.

Usage::

    python research/v2/render_v2_tables.py [--results research/results/v2] [--docs docs]

Each table replaces the text between ``<!-- BEGIN GENERATED: name -->`` and
``<!-- END GENERATED: name -->`` in the target document. Missing result files
leave the section with a note saying the measurement has not been run.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MiB = 2 ** 20
GiB = 2 ** 30


def _load(results: Path, name: str):
    path = results / f"{name}.json"
    return json.loads(path.read_text()) if path.exists() else None


def _size(n: int) -> str:
    for unit, div in (("GB", 10**9), ("MB", 10**6), ("KB", 10**3)):
        if n >= div:
            v = n / div
            return f"{v:g} {unit}" if v == int(v) else f"{v:.1f} {unit}"
    return f"{n} B"


def _replace(doc: Path, name: str, body: str, source: str) -> None:
    text = doc.read_text(encoding="utf-8")
    begin, end = f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->"
    if begin not in text or end not in text:
        raise SystemExit(f"{doc}: markers for {name!r} not found")
    block = f"{begin}\n*(generated by `research/v2/render_v2_tables.py` from `{source}`)*\n\n{body.strip()}\n{end}"
    text = re.sub(re.escape(begin) + r".*?" + re.escape(end), lambda _: block, text, flags=re.S)
    doc.write_text(text, encoding="utf-8")


def _env_line(env: dict) -> str:
    git = env.get("git", {})
    return (f"Machine: {env.get('platform')}, {env.get('cpu_count')} logical CPUs, Python {env.get('python')}; "
            f"vnx-dna {env.get('vnxdna_version')} at commit `{(git.get('commit') or 'unknown')[:12]}` (dirty={git.get('dirty')}).")


# ---------------------------------------------------------------- scale matrix
def scale_tables(data: dict) -> dict[str, str]:
    runs = [r for r in data["runs"] if r.get("stages") and r.get("status")]  # finished runs only
    out = {}
    lines = [_env_line(data["environment"]), "",
             f"Pattern `{data['pattern']}`, seed {data['seed']}, profile `{data['profile']}`, default workers. Every stage is the "
             "installed CLI in its own process; peak RAM is the sampled sum of RSS over the process tree (main process and "
             "all workers). Disk is the peak size of the run directory, including the input.", "",
             "| input | status | store | restore (container) | encode → VXS | recover from DNA | stored / input | strands | DNA bases | nt / input byte | VXS file |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in runs:
        st = r["stages"]

        def t(name):
            s = st.get(name)
            return f"{s['wall_s']:.1f} s ({r['size'] / s['wall_s'] / 1e6:.0f} MB/s)" if s else "–"
        store = (st.get("store") or {}).get("report") or {}
        enc = (st.get("encode_vxs") or {}).get("report") or {}
        lines.append(f"| {_size(r['size'])} | {r['status']} | {t('store')} | {t('restore_container')} | {t('encode_vxs')} | "
                     f"{t('recover_dna')} | {store.get('stored_bytes', 0) / r['size']:.3f} | {enc.get('strands', 0):,} | "
                     f"{enc.get('dna_bases', 0):,} | {enc.get('dna_bases', 0) / r['size']:.3f} | "
                     f"{r.get('strands_file_bytes', 0) / GiB:.2f} GiB |")
    out["scale-matrix"] = "\n".join(lines)

    lines = ["Peak RAM (MiB, sum over the process tree) and CPU utilisation (CPU seconds ÷ wall seconds) per stage:", "",
             "| input | store | restore | extract (container) | encode | extract (DNA) | recover | peak swap (any stage) | peak disk |",
             "|---|---|---|---|---|---|---|---|---|"]
    for r in runs:
        st = r["stages"]

        def m(name):
            s = st.get(name)
            return f"{s['peak_rss_tree_bytes'] / MiB:.0f} ({s['cpu_utilisation']:.1f}×)" if s else "–"
        swap = max((s.get("peak_swap_tree_bytes", 0) for s in st.values()), default=0)
        disk = max((s.get("peak_workdir_bytes", 0) for s in st.values()), default=0)
        lines.append(f"| {_size(r['size'])} | {m('store')} | {m('restore_container')} | {m('extract_container')} | {m('encode_vxs')} | "
                     f"{m('extract_dna')} | {m('recover_dna')} | {swap / MiB:.0f} MiB | {disk / GiB:.2f} GiB |")
    big = [r for r in runs if r["size"] >= 10**8]
    if len(big) >= 2:
        a, b = big[0], big[-1]
        verdicts = []
        for name in ("store", "encode_vxs", "recover_dna"):
            if name in a["stages"] and name in b["stages"]:
                ra, rb = a["stages"][name]["peak_rss_tree_bytes"], b["stages"][name]["peak_rss_tree_bytes"]
                verdicts.append(f"`{name}` {ra / MiB:.0f} → {rb / MiB:.0f} MiB (×{rb / ra:.2f}) while the input grew ×{b['size'] / a['size']:.0f}")
        lines += ["", "**Observed scaling** from " + _size(a["size"]) + " to " + _size(b["size"]) + ": " + "; ".join(verdicts) + "."]
    out["memory-scaling"] = "\n".join(lines)

    lines = ["| input | offset | length | container: time / peak RAM / bytes read | DNA: time / peak RAM / strands scanned (of total) | both slices equal the original |",
             "|---|---|---|---|---|---|"]
    for r in runs:
        st = r["stages"]
        c, d = st.get("extract_container"), st.get("extract_dna")
        if not c or not d:
            continue
        cr, dr = c.get("report") or {}, d.get("report") or {}
        total = ((st.get("encode_vxs") or {}).get("report") or {}).get("strands", 0)
        ra = r.get("random_access", {})
        lines.append(f"| {_size(r['size'])} | {ra.get('offset', 0):,} | {ra.get('length', 0):,} | {c['wall_s']:.2f} s / "
                     f"{c['peak_rss_tree_bytes'] / MiB:.0f} MiB / {cr.get('container_bytes_read', 0):,} B | {d['wall_s']:.2f} s / "
                     f"{d['peak_rss_tree_bytes'] / MiB:.0f} MiB / {dr.get('strands_processed', 0):,} ({total:,}) | "
                     f"{r.get('random_access_container_match') and r.get('random_access_dna_match')} |")
    out["random-access"] = "\n".join(lines)

    ten = [r for r in runs if r["size"] >= 10**10]
    if ten:
        r = ten[-1]
        st = r["stages"]
        enc = st["encode_vxs"]["report"] or {}
        store = st["store"]["report"] or {}
        rec = st["recover_dna"]
        total_time = sum(s["wall_s"] for s in st.values())
        lines = [f"| item | value |", "|---|---|",
                 f"| input | {r['size']:,} bytes, generated locally (`benchmark generate --size 10GB --pattern {data['pattern']} --seed {data['seed']}`), not committed |",
                 f"| input SHA-256 (`sha256sum`) | `{r.get('input_sha256_sha256sum')}` |",
                 f"| stored (compressed) | {store.get('stored_bytes', 0):,} bytes in {store.get('chunks', 0):,} chunks ({store.get('chunks_compressed', 0):,} compressed) |",
                 f"| ECC groups | {store.get('ecc_stripes', 0):,} (64+16 each) |",
                 f"| DNA representation | {enc.get('strands', 0):,} strands × {enc.get('efficiency', {}).get('strand_nt')} nt = {enc.get('dna_bases', 0):,} bases, written incrementally to a {r.get('strands_file_bytes', 0):,}-byte VXS file |",
                 f"| store / encode / recover wall time | {st['store']['wall_s']:.0f} s / {st['encode_vxs']['wall_s']:.0f} s / {rec['wall_s']:.0f} s (all stages {total_time:.0f} s) |",
                 f"| peak RAM (process tree, any stage) | {max(s['peak_rss_tree_bytes'] for s in st.values()) / MiB:.0f} MiB |",
                 f"| peak swap (process tree) | {max(s['peak_swap_tree_bytes'] for s in st.values()) / MiB:.0f} MiB |",
                 f"| peak disk in the run directory | {max(s['peak_workdir_bytes'] for s in st.values()) / GiB:.2f} GiB |",
                 f"| recovered SHA-256 (`sha256sum`) | `{r.get('recovered_sha256_sha256sum')}` |",
                 f"| `cmp input.bin recovered.bin` | {'identical' if r.get('recovered_cmp_identical') else 'DIFFERENT'} |",
                 f"| container restore `cmp` | {'identical' if r.get('restore_container_cmp') else 'DIFFERENT'} |",
                 f"| random access at offset {r['random_access']['offset']:,} ({r['random_access']['length']:,} B) | container: {'exact' if r.get('random_access_container_match') else 'MISMATCH'}; DNA: {'exact' if r.get('random_access_dna_match') else 'MISMATCH'} |",
                 f"| result | **{r['status']}** |"]
        out["acceptance-10gb"] = "\n".join(lines)
    return out


def readme_table(scale: dict | None, corruption: dict | None, montecarlo: dict | None) -> str:
    lines = ["Measured on this project's machine (8 logical CPUs; details and reproduction in the linked docs):", "",
             "| run | result | wall time (all stages) | peak RAM (process tree) | independent check |", "|---|---|---|---|---|"]
    for r in (scale or {}).get("runs", []):
        if r["size"] < 10**9 or not r.get("stages") or not r.get("status"):
            continue
        st = r["stages"]
        lines.append(f"| {_size(r['size'])}: store → restore → encode (VXS) → random access → recover from DNA | {r['status']} | "
                     f"{sum(s['wall_s'] for s in st.values()) / 60:.1f} min | {max(s['peak_rss_tree_bytes'] for s in st.values()) / MiB:.0f} MiB | "
                     f"`sha256sum` match: {r.get('sha256_match')}, `cmp`: {'identical' if r.get('recovered_cmp_identical') else 'DIFFERENT'} |")
    if corruption:
        lines.append(f"| {_size(corruption['size'])} corruption: 50 ECC groups damaged inside the guarantee, then one beyond | "
                     f"{corruption['status']} | – | – | inside: `cmp` {'identical' if corruption.get('within_cmp_identical') else 'DIFFERENT'}; "
                     f"beyond: exit {corruption.get('beyond_exit_code')}, no output |")
    if montecarlo:
        s = montecarlo["canonical"]["summary"]
        lo, hi = s["success_ci95"]
        lines.append(f"| Monte Carlo, canonical channel (10×, 0.1 % sub, 0.01 % ins/del, 2 % dropout), consensus | "
                     f"{s['successful_recovery']}/{s['trials']} exact (95 % CI [{lo:.3f}, {hi:.3f}]) | – | – | "
                     f"undetected corruption: {s['undetected_corruption']} |")
    lines += ["", "See [docs/LARGE_FILES.md](docs/LARGE_FILES.md), [docs/BENCHMARKS.md](docs/BENCHMARKS.md) and "
              "[docs/EXPERIMENTS.md](docs/EXPERIMENTS.md). All figures are software measurements; the channel is simulated."]
    return "\n".join(lines)


def corruption_table(data: dict) -> str:
    st = data["stages"]
    within = data.get("damage_within", {})
    beyond = data.get("damage_beyond", {})
    return "\n".join([
        _env_line(data["environment"]), "",
        "| step | result |", "|---|---|",
        f"| input | {data['size']:,} B, pattern `{data['pattern']}`, seed {data['seed']}, profile `{data['profile']}` |",
        f"| damage inside the guarantee | {len(within.get('damaged_groups', []))} ECC groups each lost exactly M = 16 strands; "
        f"{within.get('strands_substituted', 0)} other strands of those groups got a substitution ({within.get('strands_deleted', 0)} strands deleted in total) |",
        f"| recover | exit {data.get('within_exit_code')}, {st['recover_within']['wall_s']:.1f} s, peak RAM {st['recover_within']['peak_rss_tree_bytes'] / MiB:.0f} MiB |",
        f"| independent check | `cmp`: {'identical' if data.get('within_cmp_identical') else 'DIFFERENT'}; `sha256sum` match: {data.get('within_sha256_match')} |",
        f"| damage beyond the guarantee | the same plus one more group losing M + 1 = 17 strands |",
        f"| recover | exit {data.get('beyond_exit_code')} (5 = insufficient redundancy), output written: {data.get('beyond_output_written')} |",
        f"| error message | `{data.get('beyond_error')}` |",
        f"| verify | reports damaged chunk(s) {data.get('verify_reported_damaged_chunks')}; ground truth {data.get('verify_expected_damaged_chunks')} |",
        f"| result | **{data.get('status')}** |"])


# ---------------------------------------------------------------- stages / profiles
def stages_table(data: dict) -> str:
    lines = [_env_line(data["environment"]), "",
             "Wall-clock seconds and throughput (MB/s of *input* bytes, except G: bytes of ECC data). One run per size, "
             "`mixed` input, default workers. CPU time of worker processes is not included in this in-process benchmark "
             "(see the scale benchmark for process-tree measurements).", ""]
    runs = data["results"]["runs"]
    names = list(runs[0]["stages"])
    lines.append("| stage | " + " | ".join(_size(r["size"]) for r in runs) + " |")
    lines.append("|---|" + "---|" * len(runs))
    for name in names:
        cells = []
        for r in runs:
            s = r["stages"][name]
            cells.append(f"{s['wall_s']:.3f} s" + (f" ({s['mb_s']:.1f} MB/s)" if s.get("mb_s") else ""))
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def profiles_table(data: dict) -> str:
    h = data["harsh_channel"]
    lines = [_env_line(data["environment"]), "", data["input"] + ".", "",
             f"Harsh channel for the robustness column: coverage {h['coverage']} ({h['coverage_model']}), substitution {h['substitution_rate']}, "
             f"insertion {h['insertion_rate']}, deletion {h['deletion_rate']}, dropout {h['dropout_rate']}; cluster + consensus.", "",
             "| profile | outer code | strand | stored / input | nt / input byte | nt / stored byte | store | encode | decode | exact recovery (harsh channel) | 95 % CI |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in data["rows"]:
        o = r["options"]
        s = r["harsh_channel"]["summary"]
        lo, hi = s["success_ci95"]
        lines.append(f"| {r['profile']} | {o['data_shards']}+{o['parity_shards']} | {r['strand_nt']} nt | {r['stored_bytes'] / r['input_bytes']:.3f} | "
                     f"{r['bases_per_original_byte']:.3f} | {r['bases_per_stored_byte']:.3f} | {r['store_s']:.2f} s | {r['encode_s']:.2f} s | "
                     f"{r['decode_s']:.2f} s | {s['successful_recovery']}/{s['trials']} | [{lo:.3f}, {hi:.3f}] |")
    return "\n".join(lines)


# ---------------------------------------------------------------- channel experiments
def _row(r: dict, label: str) -> str:
    s = r["summary"]
    lo, hi = s["success_ci95"]
    return (f"| {label} | {'cluster + consensus' if r['consensus'] else 'direct'} | {s['successful_recovery']}/{s['trials']} | "
            f"[{lo:.3f}, {hi:.3f}] | {s['detected_failures']} | {s['undetected_corruption']} | "
            f"{(s['mean_reads_per_strand'] or 0):.2f} | {s['mean_groups_repaired'] or 0:.1f} | {s['max_erasures_in_any_group']} |")


HEADER = ("| point | read processing | exact recovery | 95 % Wilson CI | failed (detected) | undetected corruption | "
          "mean reads/strand | mean groups repaired | worst group erasures |\n|---|---|---|---|---|---|---|---|---|")


def coverage_table(data: dict) -> str:
    base = data["rows"][0]["channel"]
    return "\n".join([data["input"] + f"; channel: substitution {base['substitution_rate']}, insertion {base['insertion_rate']}, "
                      f"deletion {base['deletion_rate']}, dropout {base['dropout_rate']}, coverage model {base['coverage_model']}.", "", HEADER]
                     + [_row(r, f"coverage {r['channel']['coverage']:g}x") for r in data["rows"]])


def errors_table(data: dict) -> str:
    lines = [data["input"] + ".", "", HEADER]
    for r in data["rows"]:
        label = f"substitution {r['rate']}" if r["axis"] == "substitution" else f"insertion = deletion = {r['rate']}"
        lines.append(_row(r, label))
    return "\n".join(lines)


def abundance_table(data: dict) -> str:
    return "\n".join([data["input"] + ".", "", HEADER] + [_row(r, f"sigma {r['sigma']}") for r in data["rows"]])


def chunks_table(data: dict) -> str:
    lines = [_env_line(data["environment"]), "", data["input"] + ".", "",
             "| chunk size | store | encode | recover from DNA | random access: container (bytes read) | random access: DNA (strands read) | peak RAM store / encode / recover | chunks | identical |",
             "|---|---|---|---|---|---|---|---|---|"]
    for r in data["rows"]:
        st = r["stages"]
        lines.append(f"| {r['chunk_size'] // 1024:,} KiB | {st['store']['wall_s']:.2f} s | {st['encode']['wall_s']:.2f} s | {st['recover']['wall_s']:.2f} s | "
                     f"{st['extract_container']['wall_s']:.2f} s ({st['extract_container']['report']['container_bytes_read']:,} B) | "
                     f"{st['extract_dna']['wall_s']:.2f} s ({st['extract_dna']['report']['strands_processed']:,}) | "
                     f"{st['store']['peak_rss_tree_bytes'] / MiB:.0f} / {st['encode']['peak_rss_tree_bytes'] / MiB:.0f} / "
                     f"{st['recover']['peak_rss_tree_bytes'] / MiB:.0f} MiB | {st['store']['report']['chunks']:,} | {r['identical']} |")
    return "\n".join(lines)


def montecarlo_table(data: dict) -> str:
    lines = [_env_line(data["environment"]), "", HEADER]
    c, d = data["canonical"], data["direct"]
    lines.append(_row(c, f"canonical channel, {data['inputs']['canonical']}"))
    lines.append(_row(d, f"coverage 5, substitution 0.001, dropout 0.02, {data['inputs']['direct']}"))
    fails = {**c["summary"]["failures_by_category"]}
    lines += ["", f"Runtime: {data['runtime_s']:.0f} s for {c['summary']['trials'] + d['summary']['trials']:,} trials. "
              f"Failure categories (canonical): {fails or 'none'}; (direct): {d['summary']['failures_by_category'] or 'none'}."]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", default="research/results/v2")
    parser.add_argument("--docs", default="docs")
    args = parser.parse_args()
    results, docs = Path(args.results), Path(args.docs)
    src = str(results).rstrip("/")
    scale = _load(results, "scale-matrix")
    if scale:
        tables = scale_tables(scale)
        _replace(docs / "LARGE_FILES.md", "scale-matrix", tables["scale-matrix"], f"{src}/scale-matrix.json")
        _replace(docs / "LARGE_FILES.md", "memory-scaling", tables["memory-scaling"], f"{src}/scale-matrix.json")
        _replace(docs / "RANDOM_ACCESS.md", "random-access", tables["random-access"], f"{src}/scale-matrix.json")
        _replace(docs / "BENCHMARKS.md", "scale-matrix", tables["scale-matrix"], f"{src}/scale-matrix.json")
        if "acceptance-10gb" in tables:
            _replace(docs / "LARGE_FILES.md", "acceptance-10gb", tables["acceptance-10gb"], f"{src}/scale-matrix.json")
    for name, fn, targets in (("corruption", corruption_table, [("LARGE_FILES.md", "corruption")]),
                              ("stages", stages_table, [("BENCHMARKS.md", "stages")]),
                              ("profiles", profiles_table, [("BENCHMARKS.md", "profiles")]),
                              ("coverage", coverage_table, [("CHANNEL_MODEL.md", "coverage"), ("EXPERIMENTS.md", "coverage")]),
                              ("errors", errors_table, [("CHANNEL_MODEL.md", "errors"), ("EXPERIMENTS.md", "errors")]),
                              ("abundance", abundance_table, [("CHANNEL_MODEL.md", "abundance")]),
                              ("montecarlo", montecarlo_table, [("EXPERIMENTS.md", "montecarlo")]),
                              ("chunks", chunks_table, [("BENCHMARKS.md", "chunks")])):
        data = _load(results, name)
        if data:
            body = fn(data)
            for doc, marker in targets:
                _replace(docs / doc, marker, body, f"{src}/{name}.json")
    readme = Path(args.docs).resolve().parent / "README.md"
    if scale or _load(results, "corruption") or _load(results, "montecarlo"):
        _replace(readme, "readme-results", readme_table(scale, _load(results, "corruption"), _load(results, "montecarlo")),
                 f"{src}/*.json")
    print("rendered")


if __name__ == "__main__":
    main()
