"""PHASE 19: /opt/vnx-dna/reports/ENVIRONMENT_READY.md, assembled only from recorded artifacts.

Sources: environment-audit/environment.json, config/hardware-capability.yaml, reports/model-benchmarks.json,
config/laya/*.yaml, reports/security/summary.json, docs/releases/v3-baseline.json, reports/validation.json,
experiment summaries and benchmark results. If a source is missing the section says so instead of guessing.
"""
from __future__ import annotations

import datetime as dt
import json
import subprocess
from pathlib import Path
from typing import Any

import yaml

from . import models, observe, paths, profile, system


def _j(p: Path) -> Any:
    return json.loads(p.read_text()) if p.exists() else None


def _gib(n: Any) -> str:
    return f"{int(n) / 2**30:.1f} GiB" if isinstance(n, (int, float)) else "?"


def _git(*a: str) -> str:
    return subprocess.run(["git", "-C", str(paths.REPO), *a], capture_output=True, text=True).stdout.strip()


def environment_ready() -> Path:
    env = _j(paths.AUDIT / "environment.json") or {}
    prof = profile.load()
    meas = prof.get("measured", {})
    mb = _j(paths.REPORTS / "model-benchmarks.json") or {}
    sec = _j(paths.REPORTS / "security" / "summary.json") or {}
    base = _j(paths.REPO / "docs" / "releases" / "v3-baseline.json") or {}
    val = _j(paths.REPORTS / "validation.json") or {}
    sysc = system.load()
    status = observe.status()
    L: list[str] = []
    a = L.append
    a("# VNX-DNA engineering environment — READY report")
    a("")
    a(f"*Generated {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M UTC} by `vnxdna report` from recorded artifacts "
      f"(repo commit `{_git('rev-parse', '--short', 'HEAD')}` on `{_git('branch', '--show-current')}`). "
      "Every number below was measured on this host; nothing is estimated unless labelled.*")
    a("")
    # 1 hardware
    c = env.get("cpu", {})
    a("## 1. Hardware profile")
    a("")
    a(f"- CPU: {c.get('model')} — {c.get('logical_cpus')} vCPU; SIMD: {', '.join(c.get('simd', []))}; **no GPU** (CPU-only design).")
    a(f"- RAM {_gib(env.get('memory', {}).get('total'))}, swap {_gib(env.get('memory', {}).get('swap_total'))}, "
      f"root disk {_gib(env.get('storage', {}).get('root', {}).get('total'))} ({_gib(env.get('storage', {}).get('root', {}).get('free'))} free at audit).")
    a(f"- Measured: sysbench CPU {meas.get('cpu_single_events_s')} ev/s (1 thread), {meas.get('cpu_multi_events_s')} ev/s "
      f"(all threads); memory {meas.get('mem_bandwidth_1t_MiBps')} MiB/s (1 t) / {meas.get('mem_bandwidth_4t_MiBps')} MiB/s (4 t); "
      f"disk seq write {meas.get('seq_write_MBps')} MB/s, read {meas.get('seq_read_MBps')} MB/s (O_DIRECT); random 16 KiB "
      f"{meas.get('rand_read_iops_16k')} r/s + {meas.get('rand_write_iops_16k')} w/s; gcc -O2 3000-function TU "
      f"{meas.get('c_compile_3000fn_O2_s')} s; Rust release hello {meas.get('rust_compile_hello_release_s')} s; "
      f"SHA-256 {meas.get('sha256', {}).get('MBps')} MB/s; zstd-3 {meas.get('zstd', {}).get('compress_MBps')}/"
      f"{meas.get('zstd', {}).get('decompress_MBps')} MB/s.")
    a("- Full profile: `/opt/vnx-dna/config/hardware-capability.yaml` (generated by `vnxdna profile`).")
    a("")
    # 2 software
    tools = env.get("tools", {})
    a("## 2. Installed software")
    a("")
    a(f"OS {env.get('os', {}).get('PRETTY_NAME')}, kernel {env.get('kernel')}. Toolchain contract: `config/toolchain.yaml` "
      "(what PHASE 4 installed, why, and the rollback script).")
    a("")
    a("| Tool | Version |")
    a("|---|---|")
    for k in ("python3.12", "uv", "gcc", "clang", "rustc", "cargo", "go", "cmake", "ninja", "node", "pnpm", "docker", "git",
              "git-lfs", "gh", "redis-server", "psql", "ollama", system.agent_cli() or "agent-cli", "gitleaks", "pip-audit", "shellcheck", "mypy", "pre-commit"):
        a(f"| {k} | {(tools.get(k) or 'missing').replace('|', '/')} |")
    a("")
    # 3 models
    a("## 3. AI models")
    a("")
    a(models.render_report(mb) if mb else "_No model benchmarks recorded (`vnxdna models bench`)._")
    a("Coding = 5 small DNA-utility functions, each executed against hidden asserts in a network-less governed sandbox; "
      "tool call = one native Ollama tool call with the right arguments. The 18 GB model is a community *abliterated* fine-tune: "
      "trust = **untrusted**, never given tools or write access.")
    a("")
    # 4 selection policy
    reg = models.registry()
    a("## 4. Model selection policy")
    a("")
    a("Deterministic (`ops/vnxops/models.py: select`): cheapest model meeting the task's minimum tier/quality that fits RAM "
      "above the 6 GiB floor; local models that do not fit **escalate** (never silently downgrade); agent tasks that edit "
      "code always use the external agent CLI under a per-role tool allowlist; one local model loaded at a time.")
    a("")
    a("| Tier | Name | Models |")
    a("|---|---|---|")
    for t, d in reg["tiers"].items():
        a(f"| {t} | {d['name']} | {', '.join(n for n, m in reg['models'].items() if m['tier'] == t) or '—'} |")
    a("")
    # 5 LAYA
    a("## 5. LAYA architecture")
    a("")
    a("`REQUEST → CLASSIFY (rules; tier-1 model fallback) → PLAN → SELECT AGENT → SELECT MODEL → CHECK RESOURCES → "
      "APPROVAL (risk) → EXECUTE (harness) → TEST → BENCHMARK → REVIEW → ACCEPT/REJECT → LOG`")
    a("")
    a("Policy: `config/laya/{policy,agents,models,resources,tools,approvals,release-gates}.yaml`. Statuses: accepted, "
      "accepted_pending_human_review (agent work stays on its `experiment/*` branch), rejected, deferred (resources), "
      "pending_approval, failed, planned. Decision records: `/opt/vnx-dna/artifacts/laya/YYYY-MM-DD/decision-*.json`.")
    a("")
    # 6 harness
    a("## 6. Harness architecture")
    a("")
    a("Task kinds: `tool` (Tier-0 argv from tools.yaml), `model` (text proposal), `agent` (the external agent CLI in a dedicated git "
      "worktree under `/opt/vnx-dna/workspaces`, `--permission-mode dontAsk`, role allowlist). Every run writes "
      "`artifacts/harness/<date>/<task>/record.json` (task id, timestamp, agent, model, repo state, input, outputs, tools, "
      "tests, benchmark, result, failure class/reason, attempts). Retries only for retryable classes, each with a different "
      "strategy (escalate_model, reduce_parallelism), max 3; tracebacks and logs are kept.")
    a("")
    # 7 MCP
    mcp = observe.mcp_health()
    a("## 7. MCP integrations")
    a("")
    a(f"{mcp['ready']}/{mcp['total']} configured servers connected: " + ", ".join(f"{s['name']} ({s['status']})" for s in mcp["servers"]) + ".")
    a("No MCP server was added. VNX-DNA agent runs get **none** (`tools.yaml mcp.allowed_servers: []`); Gmail, Drive and "
      "composio can send/write externally and are HIGH risk. Registry and risk assessment: `docs/MCP_REGISTRY.md`.")
    a("")
    # 8 queue
    q = sysc["queue"]
    a("## 8. Queue architecture")
    a("")
    a(f"`QueueBackend` → `LocalQueue` (SQLite, default, active: **{q['backend']}**), `RedisQueue` (local redis-server, DB "
      f"{q['redis']['db']}, prefix `{q['redis']['prefix']}`; reliable-queue LMOVE), `SQSQueue` (optional, "
      f"{'enabled' if q['sqs']['enabled'] else 'disabled'}; needs boto3 + AWS credentials, neither installed). "
      "`vnxdna worker` feeds queued requests through LAYA.")
    a("")
    # 9 limits
    a("## 9. Resource limits")
    a("")
    a("| Limit | Value | Formula |")
    a("|---|---|---|")
    for k, v in prof.get("limits", {}).items():
        val_s = _gib(v["value"]) if isinstance(v["value"], int) and v["value"] > 2**24 else v["value"]
        a(f"| {k} | {val_s} | {v['formula']} |")
    a("")
    a("Enforced by `vnxdna.slice` (CPUQuota/MemoryHigh/MemoryMax/MemorySwapMax/TasksMax), per-job scopes, admission control "
      "and the `vnxdna-governor` watchdog (OK/ELEVATED/DANGER/CRITICAL; freeze/kill/unload act only inside vnxdna.slice). "
      f"Current level: **{status['governor']['level']}**.")
    a("")
    # 10 security
    a("## 10. Security status")
    a("")
    if sec:
        a(f"- gitleaks (full history): {sec['gitleaks']['findings']} findings after the reviewed allowlist (`.gitleaksignore`: "
          "test-only fixture keys, by fingerprint).")
        a(f"- pip-audit (hashed lock): {sec['pip_audit']['vulnerabilities']} known vulnerabilities.")
        a(f"- SBOM: {sec['sbom']['components']} components → `/opt/vnx-dna/reports/security/sbom.cdx.json` (CycloneDX).")
        a(f"- Tracked secret-like files: {len(sec['tracked_secret_files'])}; permission issues: {sum(not p['ok'] for p in sec['permissions'])}; "
          f"shell/eval sites flagged: {len(sec['subprocess_audit'])}.")
    a("- Host findings (not changed; owner decision): see `/opt/vnx-dna/environment-audit/recommendations.md` "
      "(SSH password + root login enabled; ufw 8000/8001 open to any).")
    a("")
    # 11/13 git + repo
    a("## 11. Git status / 13. Repository status")
    a("")
    a(f"- Canonical repository: `{sysc['repository']['canonical_remote']}`.")
    a(f"- Environment work: `{paths.REPO}` on `{_git('branch', '--show-current')}` @ `{_git('rev-parse', '--short', 'HEAD')}` "
      f"({len([x for x in _git('status', '--porcelain').splitlines() if x])} uncommitted paths); "
      f"{_git('rev-list', '--count', 'v3.0.0..HEAD')} commits ahead of v3.0.0; not pushed, not merged.")
    a("- Local `development` branch created at v3.0.0. `main` and tag `v3.0.0` untouched.")
    a("- `/root/VSnexustechnologies-` (vnx-dna/v2, 2 uncommitted test edits not made by this work), `/root/vnx-dna-new` and "
      "`/srv/vsnexus/vnx-dna` (older prototypes) were backed up and left untouched.")
    a("")
    # 12 baseline
    a("## 12. V3 baseline status")
    a("")
    if base:
        t = base["tests"]
        a(f"Protected baseline `v3.0.0` = `{base['commit']}`: {t['passed']}/{t['tests']} tests passed in {t['time_s']} s on the "
          f"pristine worktree; e2e {base['e2e']['roundtrip']['outcome']} (SHA-256 identical, reproducible: {base['e2e']['reproducible']}); "
          "smoke + standard benchmarks recorded. Document: `docs/releases/V3_BASELINE.md`.")
    a("")
    # 14/15 failures + issues
    a("## 14. Known failures")
    a("")
    failures = [r for r in val.get("results", []) if r["result"] != "PASS"]
    if not val:
        a("_Validation not run._")
    elif failures:
        for r in failures:
            a(f"- {r['check']}: {r['result']} — `{json.dumps(r['evidence'], default=str)[:300]}`")
    else:
        a(f"None: all {len(val['results'])} validation checks passed (`/opt/vnx-dna/reports/validation.json`, {val['at']}).")
    a("")
    a("## 15. Unresolved issues (need an owner decision)")
    a("")
    issues = yaml.safe_load((paths.REPO / "config" / "unresolved.yaml").read_text()) if (paths.REPO / "config" / "unresolved.yaml").exists() else []
    for i in issues or []:
        a(f"- **{i['title']}** — {i['detail']}")
    a("")
    a("## 16. Recommended next step")
    a("")
    a("1. Review and merge `feature/environment` into `development` (exact SHA confirmation, as for every merge).")
    a("2. Decide the unresolved items above (dependency caps, SSH hardening).")
    a("3. Start V4 (architecture hardening) on `feature/v4-*` from `development` through LAYA: "
      "`vnxdna laya plan \"design the V4 architecture hardening plan from docs/ROADMAP_V4_V50.md\"` → approve → run.")
    a("")
    a("## 17. Operating commands")
    a("")
    a("```")
    for line in ["vnxdna status                      # one-screen status",
                 "vnxdna doctor [--deep]             # checks + fixes (deep: e2e, ops tests, bench smoke)",
                 "vnxdna test fast|full|ops|all      # governed test runs",
                 "vnxdna e2e                         # encode/decode + SHA-256 + reproducibility",
                 "vnxdna benchmark --system          # hardware benchmark (quick)",
                 "vnxdna benchmark --dna --suite smoke|standard|large",
                 "vnxdna experiment smoke|error-models|constraints",
                 "vnxdna laya plan|run \"request\"     # LAYA decision (plan = no execution)",
                 "vnxdna laya approve <decision-id>  # approve a pending high-risk decision",
                 "vnxdna laya list                   # recent decisions",
                 "vnxdna agent <role> \"request\"      # route to an agent role through LAYA",
                 "vnxdna queue put \"request\" && vnxdna worker --max 1",
                 "vnxdna run --class build --mem 2GiB -- <cmd>   # any heavy command under the governor",
                 "vnxdna governor [status|tick]      # pressure level, active jobs",
                 "vnxdna models list|bench|select <task>",
                 "vnxdna release check --version V4  # acceptance gates → release/V4_ACCEPTANCE_REPORT.md",
                 "vnxdna security                    # gitleaks, pip-audit, SBOM, permissions",
                 "vnxdna improve                     # observe → propose (never edits code)",
                 "vnxdna backup <paths> --label X    # bundle + tar with SHA-256 manifest",
                 "vnxdna baseline [--measure]        # V3 baseline manifest",
                 "vnxdna validate                    # the 13 environment validation checks",
                 "vnxdna report                      # regenerate this file",
                 "vnxdna encode|decode|verify|inspect|simulate …   # forwarded to the vnx-dna library CLI"]:
        a(line)
    a("```")
    a("")
    a("Rollback: `/opt/vnx-dna/rollback/` (governor-uninstall.sh, toolchain-uninstall.sh, files-created.txt). Backups: "
      "`/opt/vnx-dna/backups/` (`vnxdna backup --verify DIR`).")
    p = paths.REPORTS / "ENVIRONMENT_READY.md"
    paths.ensure(p.parent)
    p.write_text("\n".join(L) + "\n")
    return p
