"""Generate ``public_paths.json``: every ``vnxdna.*`` module path and attribute used outside ``src/``.

Run once from the repository root, before the V6 Phase 2 module moves (V6_ARCHITECTURE §7.1 M0)::

    PYTHONPATH=src python tests/architecture/generate_public_paths.py

It walks ``tests/``, ``experiments/`` and ``benchmarks/`` with :mod:`ast` and records

* ``modules``: every ``vnxdna`` module imported (``import vnxdna.x``, ``from vnxdna.x import y`` where ``y`` is a module,
  and ``python -m vnxdna.x`` in these trees or in README, Dockerfile, docs/ and CI, marked runnable);
* ``attributes``: ``[module, name]`` for every name imported from a ``vnxdna`` module and every attribute read or
  monkeypatched on a name bound to a ``vnxdna`` module (``from vnxdna.v4 import decoder as de`` … ``de.Spill``).

The generated list is committed and is never regenerated by the migration: it is the contract the moved code must keep.
"""
from __future__ import annotations

import ast
import importlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCAN = ("tests", "experiments", "benchmarks")
DASH_M = re.compile(r"""(?:-m["']?\s*,?\s*["']?)(vnxdna(?:\.[A-Za-z_][A-Za-z0-9_]*)*)""")


def is_module(name: str) -> bool:
    try:
        importlib.import_module(name)
        return True
    except ImportError:
        return False


def scan_file(path: Path, modules: dict, attrs: set) -> None:
    text = path.read_text(encoding="utf-8", errors="replace")
    for m in DASH_M.finditer(text):
        modules.setdefault(m.group(1), {"runnable": False})["runnable"] = True
    if path.suffix != ".py":
        return
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return
    bound: dict[str, str] = {}               # local name -> vnxdna module it refers to
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name == "vnxdna" or a.name.startswith("vnxdna."):
                    modules.setdefault(a.name, {"runnable": False})
                    if a.asname:
                        bound[a.asname] = a.name
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module and \
                (node.module == "vnxdna" or node.module.startswith("vnxdna.")):
            modules.setdefault(node.module, {"runnable": False})
            for a in node.names:
                if a.name == "*":
                    continue
                full = f"{node.module}.{a.name}"
                if is_module(full):
                    modules.setdefault(full, {"runnable": False})
                    bound[a.asname or a.name] = full
                else:
                    attrs.add((node.module, a.name))
    for node in ast.walk(tree):
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name) and node.value.id in bound:
            target = bound[node.value.id]
            sub = f"{target}.{node.attr}"
            if is_module(sub):
                modules.setdefault(sub, {"runnable": False})
            else:
                attrs.add((target, node.attr))
        # monkeypatch.setattr(module_alias, "name", ...)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "setattr" \
                and len(node.args) >= 2 and isinstance(node.args[0], ast.Name) and node.args[0].id in bound \
                and isinstance(node.args[1], ast.Constant) and isinstance(node.args[1].value, str):
            attrs.add((bound[node.args[0].id], node.args[1].value))


def main() -> int:
    modules: dict = {}
    attrs: set = set()
    for d in SCAN:
        for p in sorted((ROOT / d).rglob("*")):
            if p.is_file() and p.suffix in (".py", ".sh", ".md", ".yml", ".yaml", ".toml", ".txt") and "fixtures" not in p.parts[:3]:
                scan_file(p, modules, attrs)
    for p in [ROOT / "README.md", ROOT / "Dockerfile", *sorted((ROOT / "docs").rglob("*.md")), *sorted((ROOT / ".github").rglob("*.yml"))]:
        for m in DASH_M.finditer(p.read_text(encoding="utf-8", errors="replace")):   # documented ``python -m`` entry points
            modules.setdefault(m.group(1), {"runnable": False})["runnable"] = True
    # keep only paths that resolve today (a typo in a comment is not a contract)
    mods = {m: v for m, v in sorted(modules.items()) if is_module(m)}
    good = []
    for mod, name in sorted(attrs):
        if mod in mods and hasattr(importlib.import_module(mod), name):
            good.append([mod, name])
    out = {"generated_from": "tests/, experiments/, benchmarks/ at the pre-refactor tree (V6 Phase 2, M0)",
           "modules": [{"module": m, "runnable": v["runnable"]} for m, v in mods.items()], "attributes": good}
    (Path(__file__).parent / "public_paths.json").write_text(json.dumps(out, indent=1) + "\n")
    print(f"{len(mods)} modules, {len(good)} attributes", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
