"""Render the measured V3 results (JSON) into docs/. No number in these tables is typed by hand.

Usage::

    python research/v3/render_v3_tables.py [--results research/results/v3] [--docs docs]

Each table replaces the text between ``<!-- BEGIN GENERATED: name -->`` and ``<!-- END GENERATED: name -->``.
A missing result file leaves a note that the measurement has not been run.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MiB = 2 ** 20


def load(results: Path, name: str):
    path = results / f"{name}.json"
    return json.loads(path.read_text()) if path.exists() else None


def size(n: int) -> str:
    for unit, div in (("GB", 10**9), ("MB", 10**6), ("KB", 10**3)):
        if n >= div:
            v = n / div
            return f"{v:g} {unit}" if v == int(v) else f"{v:.1f} {unit}"
    return f"{n} B"


def replace(doc: Path, name: str, body: str, source: str) -> None:
    text = doc.read_text(encoding="utf-8")
    begin, end = f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->"
    if begin not in text or end not in text:
        raise SystemExit(f"{doc}: markers for {name!r} not found")
    block = f"{begin}\n*(generated by `research/v3/render_v3_tables.py` from `{source}`)*\n\n{body.strip()}\n{end}"
    doc.write_text(re.sub(re.escape(begin) + r".*?" + re.escape(end), lambda _: block, text, flags=re.S), encoding="utf-8")


def env_line(env: dict) -> str:
    git = env.get("git", {})
    return (f"Machine: {env.get('platform')}, {env.get('cpu_count')} logical CPUs, Python {env.get('python')}; "
            f"vnx-dna {env.get('vnxdna_version')} at commit `{(git.get('commit') or 'unknown')[:12]}` (dirty={git.get('dirty')}).")


# ---------------------------------------------------------------- scale: V2 vs V3
STAGES = (("store", "store"), ("restore_container", "restore"), ("encode_vxs", "encode → VXS"), ("recover_dna", "recover from DNA"),
          ("extract_container", "random access (container)"), ("extract_dna", "random access (DNA)"))


def scale_table(v2: dict | None, v3: dict | None) -> str:
    if not v3:
        return "*Not measured yet.*"
    lines = []
    for label, data in (("V2 (2.0.0)", v2), ("V3", v3)):
        if data:
            lines.append(f"- {label}: {env_line(data['environment'])}")
    lines += ["", "Pattern `mixed`, seed 42, profile `balanced`, default workers; every stage is the installed CLI in its own process. "
              "Cells: wall time / peak RAM of the process tree (sum of RSS over the main process and its workers).", "",
              "| input | version | status | " + " | ".join(label for _, label in STAGES) + " | SHA-256 and byte equality |",
              "|---|---|---|" + "---|" * len(STAGES) + "---|"]
    runs2 = {r["size"]: r for r in (v2 or {}).get("runs", []) if r.get("stages")}
    for r3 in [r for r in v3["runs"] if r.get("stages")]:
        for label, run in (("V2", runs2.get(r3["size"])), ("V3", r3)):
            if run is None:
                continue
            cells = []
            for key, _ in STAGES:
                st = run["stages"].get(key)
                cells.append(f"{st['wall_s']:.2f} s / {st['peak_rss_tree_bytes'] / MiB:.0f} MiB" if st else "–")
            equal = all(run.get(k) for k in ("sha256_match", "recovered_cmp_identical", "restore_container_cmp",
                                             "random_access_container_match", "random_access_dna_match"))
            lines.append(f"| {size(run['size'])} | {label} | {run.get('status')} | " + " | ".join(cells) + f" | {equal} |")
    return "\n".join(lines)


def scale_memory_table(v3: dict | None) -> str:
    if not v3:
        return "*Not measured yet.*"
    lines = ["| input | stage | wall | CPU (user+sys) | CPU utilisation | peak RAM (tree) | largest process | peak disk (run dir) |",
             "|---|---|---|---|---|---|---|---|"]
    for run in [r for r in v3["runs"] if r.get("stages")]:
        for key, label in STAGES[:4]:
            st = run["stages"].get(key)
            if not st:
                continue
            lines.append(f"| {size(run['size'])} | {label} | {st['wall_s']:.2f} s | {st['cpu_user_s'] + st['cpu_system_s']:.1f} s | "
                         f"{st['cpu_utilisation']:.1f} | {st['peak_rss_tree_bytes'] / MiB:.0f} MiB | "
                         f"{st['largest_single_process_maxrss_bytes'] / MiB:.0f} MiB | {st['peak_workdir_bytes'] / MiB:,.0f} MiB |")
    return "\n".join(lines)


def density_table(v3: dict | None) -> str:
    if not v3:
        return "*Not measured yet.*"
    lines = ["| input | stored / input (zstd) | strands | DNA bases | nt per input byte | net bits per nt | ECC groups | parity strands | "
             "metadata strands | VXS file |", "|---|---|---|---|---|---|---|---|---|---|"]
    for run in [r for r in v3["runs"] if r.get("stages")]:
        enc = run["stages"]["encode_vxs"]["report"]
        eff = enc["efficiency"]
        store = run["stages"]["store"]["report"]
        lines.append(f"| {size(run['size'])} | {store['stored_bytes'] / run['size']:.3f} | {eff['strands_total']:,} | "
                     f"{eff['dna_bases_total']:,} | {eff['bases_per_original_byte']:.3f} | {eff['net_bits_per_base']:.3f} | "
                     f"{eff['ecc_groups']:,} | {eff['parity_strands']:,} | {eff['metadata_strands']:,} | {run['strands_file_bytes']:,} B |")
    return "\n".join(lines)


# ---------------------------------------------------------------- stages
def stages_table(v2: dict | None, v3: dict | None) -> str:
    if not v3:
        return "*Not measured yet.*"
    lines = [f"- V3: {env_line(v3['environment'])}"] + ([f"- V2: {env_line(v2['environment'])}"] if v2 else []) + [
        "", "Wall-clock seconds, one run per size, `mixed` input, default workers (in-process; worker CPU not included).", ""]
    sizes = [r["size"] for r in v3["runs"]]
    lines += ["| stage | " + " | ".join(f"{size(s)} V2 | {size(s)} V3" for s in sizes) + " |",
              "|---|" + "---|---|" * len(sizes)]
    v2runs = {r["size"]: r["stages"] for r in (v2 or {}).get("runs", [])}
    names = sorted(v3["runs"][0]["stages"])
    for name in names:
        cells = []
        for s in sizes:
            old = v2runs.get(s, {}).get(name)
            new = next(r["stages"] for r in v3["runs"] if r["size"] == s).get(name)
            cells += [f"{old['wall_s']:.3f}" if old else "–", f"{new['wall_s']:.3f}" if new else "–"]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


# ---------------------------------------------------------------- noisy decode, indel repair
def noisy_table(d: dict | None) -> str:
    if not d:
        return "*Not measured yet.*"
    lines = [f"{d['size']} input; {d['note']}. Machine: {d['machine']['platform']}, Python {d['machine']['python']}.",
             f"Current: `{d['versions'].get('current')}`; baseline: `{d['versions'].get('baseline')}`.", "",
             "| substitution rate | V2 restore (wall / CPU / peak RSS) | V3 restore (wall / CPU / peak RSS) | V2 exact | V3 exact | "
             "speed-up (wall) |", "|---|---|---|---|---|---|"]
    for r in d["rows"]:
        b, c = r["baseline"], r["current"]
        lines.append(f"| {r['substitution_rate']:g} | {b['wall_s']:.2f} s / {b['cpu_s']:.1f} s / {b['peak_rss_mib']:.0f} MiB (exit {b['exit']}) | "
                     f"{c['wall_s']:.2f} s / {c['cpu_s']:.1f} s / {c['peak_rss_mib']:.0f} MiB (exit {c['exit']}) | {b['exact']} | "
                     f"{c['exact']} | {r.get('speedup_wall', '–')}× |")
    return "\n".join(lines)


def indel_table(v2: dict | None, v3: dict | None) -> str:
    if not v3:
        return "*Not measured yet.*"
    lines = [f"Geometry {v3['geometry']}, {v3['reads']} reads per row, seed {v3['seed']}, search budget {v3['max_candidates']:,} "
             "hypotheses per orientation; software simulation.", "",
             "| indels (direction) | extra substitutions | V2 correct / wrong / failed | V2 ms per read | V3 correct / wrong / failed | "
             "V3 ms per read |", "|---|---|---|---|---|---|"]
    old = {(r["indels"], r["substitutions"], r.get("directions")): r for r in (v2 or {}).get("rows", [])}
    for r in v3["rows"]:
        o = old.get((r["indels"], r["substitutions"], r.get("directions")))
        lines.append(f"| {r['indels']} ({r.get('directions')}) | {r['substitutions']} | "
                     + (f"{o['correct']} / {o['wrong']} / {o['failed']} of {o['attempted']} | {o['ms_per_read']}" if o else "– | –")
                     + f" | {r['correct']} / {r['wrong']} / {r['failed']} of {r['attempted']} | {r['ms_per_read']} |")
    return "\n".join(lines)


# ---------------------------------------------------------------- sweeps
def sweep_table(d: dict | None, compare: dict | None = None) -> str:
    if not d:
        return "*Not measured yet.*"
    base = d["base_channel"]
    lines = [f"vnx-dna {d['vnxdna_version']}, profile `{d['store_options'].get('profile')}`, {d['input']['size']:,} B input "
             f"({d['strands']:,} strands of {d['strand_nt']} nt); base channel coverage {base['coverage']} ({base['coverage_model']}), "
             f"reads shuffled, seeds {base['seed']}…{base['seed'] + d['trials_per_point'] - 1}; consensus {d['consensus']}; "
             f"{d['trials_per_point']} trials per point. Undetected corruption over all points: **{d['undetected_corruption_total']}**; "
             f"internal errors: **{d['internal_errors_total']}**.", ""]
    if compare:
        lines += ["| point | exact (repairs off) | exact (repairs on) | 95% CI (on) | detected failures (on) | undetected (off / on) |",
                  "|---|---|---|---|---|---|"]
        off = {p["point"]: p for p in compare["points"]}
        for p in d["points"]:
            o = off.get(p["point"])
            lines.append(f"| {p['point']} | {o['exact'] if o else '–'}/{p['trials']} | {p['exact']}/{p['trials']} | "
                         f"[{p['ci95_low']:.3f}, {p['ci95_high']:.3f}] | {p['failed_detected']} | "
                         f"{o['undetected_corruption'] if o else '–'} / {p['undetected_corruption']} |")
    else:
        lines += ["| point | exact | 95% CI | detected failures | undetected | internal |", "|---|---|---|---|---|---|"]
        for p in d["points"]:
            lines.append(f"| {p['point']} | {p['exact']}/{p['trials']} | [{p['ci95_low']:.3f}, {p['ci95_high']:.3f}] | "
                         f"{p['failed_detected']} | {p['undetected_corruption']} | {p['internal_errors']} |")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, default=Path("research/results/v3"))
    ap.add_argument("--docs", type=Path, default=Path("docs"))
    a = ap.parse_args()
    r, docs = a.results, a.docs
    src = str(r)
    s2, s3 = load(r, "scale-v2"), load(r, "scale-v3")
    replace(docs / "BENCHMARKS.md", "v3-scale", scale_table(s2, s3), f"{src}/scale-v2.json, scale-v3.json")
    replace(docs / "BENCHMARKS.md", "v3-density", density_table(s3), f"{src}/scale-v3.json")
    replace(docs / "LARGE_FILES.md", "v3-memory", scale_memory_table(s3), f"{src}/scale-v3.json")
    replace(docs / "BENCHMARKS.md", "v3-stages", stages_table(load(r, "stages-v2"), load(r, "stages-v3")), f"{src}/stages-*.json")
    replace(docs / "BENCHMARKS.md", "v3-noisy", noisy_table(load(r, "noisy-decode")), f"{src}/noisy-decode.json")
    replace(docs / "SYNCHRONIZATION.md", "v3-indel", indel_table(load(r, "indel-v2"), load(r, "indel-v3")), f"{src}/indel-*.json")
    replace(docs / "ERROR_MODEL.md", "v3-sweep-cov1",
            sweep_table(load(r, "sweep-cov1-repairs-on"), load(r, "sweep-cov1-repairs-off")), f"{src}/sweep-cov1-*.json")
    replace(docs / "ERROR_MODEL.md", "v3-sweep-cov5", sweep_table(load(r, "sweep-cov5-consensus")), f"{src}/sweep-cov5-consensus.json")


if __name__ == "__main__":
    main()
