"""Shard-level error-correction interface.

`data_shards` (K) holds original bytes; `parity_shards` (M) holds redundant
codewords. A codec must reconstruct any K available shards from K+M total
shards. Invalid shard checksums are passed as erasures, not trusted data.
"""
from typing import Protocol
class ShardECC(Protocol):
    data_shards:int; parity_shards:int
    def encode(self, data_shards:list[bytes])->list[bytes]: ...
    def verify(self, shards:list[bytes|None])->bool: ...
    def recover(self, shards:list[bytes|None])->list[bytes]: ...
    def decode(self, shards:list[bytes|None])->list[bytes]: ...
